### ISSUE TITLE
Remove sanic-compress

### ISSUE THREAD

**Issue by koug44** [mekicha/awesome-sanic#8]
Hello,

I'm looking forward to this plugin but it does not seem to be maintained anymore and looking at the MR, there's a lot of issues with it.

Damien

**Comment by nm17** [comment]
https://github.com/michaelchisari/sanic_brogz seems to be more maintained, maybe it's a good idea to replace it, instead of deleting it.

**Comment by koug44** [comment]
Yes, I think you're right
